### ISSUE TITLE
[HealthbarImmune] Issue: SOTS - IMMUNE text doesn't replace healthbar text

### ISSUE THREAD

**Issue by treacherousfiend** [DestroyedClone/RoR2-HealthbarImmune#1]
**Describe the bug**
Through some sort of miracle, this mod still sort of works after the SotS update.
The bar still turns yellow when you are immune, but it unfortunately does not replace the HP number with the "IMMUNE" text now.

**To Reproduce**
1. Make sure you're on the latest version of the game (DLC not required)
2. Become immune on any character

**Expected behavior**
Behavior would match the mod prior to SotS release, turning the HP bar yellow _and_ replacing the HP number with text that says "IMMUNE"

**Additional context**
N/A

**Comment by DestroyedClone** [comment]
Confirmed.

**Comment by DestroyedClone** [comment]
Fixed with https://github.com/DestroyedClone/RoR2-HealthbarImmune/commit/d193aecf34e5fcdbed356ca4b751ec0ee9039eb6
It'll be updated shortly on the thunderstore.
